function Head() {
  <div className={styles.container}>
    <Head>
      <title>Movie-gallery</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  </div>;
}

export default Head;
